### PR TITLE
ci: Integrate Release-please action and config

### PR DESCRIPTION
**Pull request by JesperDramsch**
This is a proposal to manage our release process and changelog updates using [release-please](https://github.com/googleapis/release-please)). This was originally proposed by @dnerini. 

From the docs:
> Release Please automates CHANGELOG generation, the creation of GitHub releases, and version bumps for your projects.
> 
> It does so by parsing your git history, looking for [Conventional Commit messages](https://www.conventionalcommits.org/), and creating release PRs.
> 
> It does not handle publication to package managers or handle complex branch management.

## Analysis of Alternatives
I have evaluated alternatives such as [Python Semantic Releases](https://python-semantic-release.readthedocs.io/en/latest/index.html) and a few others, but release-please seems like the most mature project that would work across all packages, including mono-repos and helps with the changelog as well.

It is to be said, that the documentation of release-please is not very beginner-friendly, so it will probably take a few tries to set up correctly until we have a working setup usable across all of Anemoi.

For reference, there is a archived repo showing the [setup for mono-repos](https://github.com/amarjanica/release-please-monorepo-example/blob/main/release-please-config.json) if that is necessary

## How to run
They have implemented a corresponding [Action](https://github.com/marketplace/actions/release-please-action).

## Additional Information

I have mainly used the [Manifest Releaser](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md) document to set up the configs and action.
Additionally, I looked at the [JSON schema](https://github.com/googleapis/release-please/blob/main/schemas/config.json) to evaluate if there are additional relevant config entries.

## Caveat

All automated log generators require some sort of commit convention.

Since we squash-merge anyways, we can limit the effect on new contributors by only requiring PRs to follow Conventional Commits. This seems like an acceptable half-way solution that doesn't get in the way of quick development, but introduces some structure in the code itself.

### CODE REVIEW

**Comment by dnerini** [comment]
@OpheliaMiralles @icedoom888 @frazane please take this opportunity to have a closer look at release-please and feel free to leave your feedback. The idea would be to roll out this to all anemoi repos.

**Comment by dnerini** [comment]
@JesperDramsch squash commits seems to be right way to go with release-please (see [here](https://github.com/googleapis/release-please?tab=readme-ov-file#linear-git-commit-history-use-squash-merge)). This would limit the need to follow commit conventional messages to PR titles only.

**Review by b8raoult — COMMENTED** [review]
Double // comments are not valid in JSON. I guess the `. release-please-config.json` file is merely a template.

**Comment by JesperDramsch** [comment]
> Double // comments are not valid in JSON. I guess the `. release-please-config.json` file is merely a template.

Oh. Thanks for catching this!

**Comment by JesperDramsch** [comment]
> @JesperDramsch squash commits seems to be right way to go with release-please (see [here](https://github.com/googleapis/release-please?tab=readme-ov-file#linear-git-commit-history-use-squash-merge)). This would limit the need to follow conventional commit messages to PR titles only.

Ah fantastic @dnerini. I'm glad this resonates, I hope the action I added to check these will help with this.

**Comment by frazane** [comment]
Seems like a great idea, thank you! Question: now that we're in major version zero (early development) will breaking changes by default result in a minor version bump?

**Comment by JesperDramsch** [comment]
> Seems like a great idea, thank you! Question: now that we're in major version zero (early development) will breaking changes by default result in a minor version bump?

Yes exactly. So currently I have configured it so that breaking changes bump minor and features bump patch.

**Review by HCookie — APPROVED** [review]

**Pull request merged**
