### PR TITLE
[draft] bugfix: fully resolve mount points

### LINKED ISSUE #26: Discrepancy between paths in `provenance` when working on a mounted filesystem
### What happened?

When calling function `gather_provenance_info()` on the LUMI lustre-filesystem, I get following error:
```python
git.exc.NoSuchPathError: /pfs/lustrep4<data>/src/anemoi-utils/src/anemoi/utils/__init__.py
```
Looking at the path, some replacing clearly went wrong.
It turns out in function `anemoi.utils.provenance._module_version(full)`, the `roots` are derived with `sysconfig.get_paths()`:
https://github.com/ecmwf/anemoi-utils/blob/b711128288564f8e2165cf2850ffeac126f0028a/src/anemoi/utils/provenance.py#L122-L125

Turns out that on the LUMI lustre filesystem this gives:
```python
{'stdlib': '/opt/conda/envs/conda_container_env/lib/python3.12', 'platstdlib': '/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12', 'purelib': '/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages', 'platlib': '/scratch/project_465001235/vanginde/anemoi-lam-venv/lib/python3.12/site-packages', 'include': '/opt/conda/envs/conda_container_env/include/python3.12', 'platinclude': '/opt/conda/envs/conda_container_env/include/python3.12', 'scripts': '/scratch/project_465001235/vanginde/anemoi-lam-venv/bin', 'data': '/scratch/project_465001235/vanginde/anemoi-lam-venv'}
```
i.e. all are defined as you typically see them in the terminal.  

However when in the function `versions`,  the path of module is derived with `path = module.__file__`
https://github.com/ecmwf/anemoi-utils/blob/b711128288564f8e2165cf2850ffeac126f0028a/src/anemoi/utils/provenance.py#L80-L81
on LUMI this gives for `anemoi.utils`:
```python
/pfs/lustrep4/scratch/project_465001235/vanginde/anemoi-lam-venv/src/anemoi-utils/src/anemoi/utils/__init__.py
```
So when some replacing is done in this `versions`-function, some part of the actual true path is not replaced giving the faulty path as seen above.

### What are the steps to reproduce the bug?

On a mounted-filesystem:
```python
import anemoi.utils

anemoi.utils.provenance.gather_provenance_info() 
```
### Version

v0.4.1

### Platform (OS and architecture)

Linux 

### Relevant log output

_No response_

### Accompanying data

_No response_

### Organisation

_No response_

### PR DESCRIPTION
**Pull request by mpvginde**
Fixes #26

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-utils?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-utils?pullRequest=27) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-utils?pullRequest=27) it.</sub>

**Comment by mpvginde** [comment]
I have added one `os.path.realpath()` to fix my specific bug, but it might be needed in other places to for consistency?

**Comment by HCookie** [comment]
Can you detail the bug that occured that needs this fix?

**Comment by mpvginde** [comment]
The detailed info is in the Issue #26

**Comment by HCookie** [comment]
Once you add a changelog entry, this PR can be merged

**Review by HCookie — APPROVED** [review]

**Pull request merged**
